"use client";

import { useEffect, useState } from "react";
import {
  Bell,
  CheckCircle2,
  Clock,
  Radio,
  Wifi,
  WifiOff,
} from "lucide-react";
import { AppShell } from "@/components/AppShell";
import { io } from "socket.io-client";

const API_URL =
  process.env.NEXT_PUBLIC_API_URL || "http://localhost:3000/api";

const SOCKET_URL =
  process.env.NEXT_PUBLIC_SOCKET_URL || "http://localhost:3010";

export default function NotificationsPage() {
  const [notifications, setNotifications] = useState<any[]>([]);
  const [socketConnected, setSocketConnected] = useState(false);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function load() {
      try {
        setLoading(true);

        const response = await fetch(`${API_URL}/notifications`);
        const data = await response.json();

        if (!response.ok) {
          setNotifications([]);
          return;
        }

        setNotifications(Array.isArray(data) ? data : []);
      } catch {
        setNotifications([]);
      } finally {
        setLoading(false);
      }
    }

    load();
  }, []);

  useEffect(() => {
    const token =
      localStorage.getItem("smart_campus_access_token") ||
      localStorage.getItem("accessToken") ||
      localStorage.getItem("token");

    if (!token) return;

    const socket = io(SOCKET_URL, {
      auth: { token },
      transports: ["websocket"],
    });

    socket.on("connect", () => {
      setSocketConnected(true);
    });

    socket.on("connect_error", () => {
      setSocketConnected(false);
    });

    socket.on("notification:new", (notification) => {
      setNotifications((current) => [notification, ...current]);
    });

    socket.on("notification:unread-count", () => {
      // Reserved for unread counter updates.
    });

    socket.on("disconnect", () => {
      setSocketConnected(false);
    });

    return () => {
      socket.disconnect();
    };
  }, []);

  return (
    <AppShell>
      <section className="rounded-3xl bg-gradient-to-r from-[#002b5c] via-[#003b7a] to-[#8b0000] p-10 text-white shadow-xl">
        <p className="text-sm font-bold uppercase tracking-[0.3em] text-[#f4c430]">
          Smart Campus Module 3
        </p>

        <h1 className="mt-4 text-5xl font-extrabold">Notifications</h1>

        <p className="mt-4 max-w-3xl text-lg text-white/80">
          Review platform notifications generated by Smart Campus services and
          receive real-time updates when new events are published.
        </p>

        <div className="mt-8 flex flex-wrap gap-3">
          <Badge text="RabbitMQ Events" />
          <Badge text="WebSocket Updates" />
          <Badge text="Redis Counters" />
          <Badge text="Notification Service" />
        </div>
      </section>

      <section className="mt-8 grid gap-5 md:grid-cols-3">
        <InfoCard
          icon={<Bell />}
          title="Total Notifications"
          value={notifications.length}
          text="Messages available for the current user."
        />

        <InfoCard
          icon={socketConnected ? <Wifi /> : <WifiOff />}
          title="Real-Time Connection"
          value={socketConnected ? "Online" : "Offline"}
          text="WebSocket connection status."
        />

        <InfoCard
          icon={<Radio />}
          title="Event Delivery"
          value="Enabled"
          text="Notifications are delivered from platform events."
        />
      </section>

      <section className="mt-8 rounded-3xl bg-white p-8 shadow-sm ring-1 ring-slate-200">
        <div className="mb-6 flex flex-col justify-between gap-3 md:flex-row md:items-end">
          <div>
            <h2 className="text-2xl font-extrabold text-[#002b5c]">
              Notification Center
            </h2>
            <p className="mt-2 text-sm text-slate-500">
              New notifications appear automatically when the WebSocket
              connection is active.
            </p>
          </div>

          <span
            className={`rounded-full px-4 py-2 text-sm font-bold ring-1 ${
              socketConnected
                ? "bg-green-50 text-green-700 ring-green-200"
                : "bg-slate-50 text-slate-600 ring-slate-200"
            }`}
          >
            {socketConnected ? "Connected" : "Not connected"}
          </span>
        </div>

        {loading ? (
          <div className="rounded-2xl bg-slate-50 p-6 text-slate-500">
            Loading notifications...
          </div>
        ) : notifications.length === 0 ? (
          <div className="rounded-2xl bg-slate-50 p-10 text-center ring-1 ring-slate-200">
            <Bell className="mx-auto text-slate-400" size={42} />

            <h3 className="mt-4 text-xl font-extrabold text-[#002b5c]">
              No notifications yet
            </h3>

            <p className="mt-2 text-slate-500">
              When platform events occur, notifications will appear here.
            </p>
          </div>
        ) : (
          <div className="space-y-4">
            {notifications.map((notification, index) => (
              <NotificationItem
                key={notification.id || index}
                notification={notification}
              />
            ))}
          </div>
        )}
      </section>
    </AppShell>
  );
}

function NotificationItem({ notification }: { notification: any }) {
  return (
    <div className="rounded-2xl bg-slate-50 p-5 ring-1 ring-slate-200 transition hover:bg-white hover:shadow-sm">
      <div className="flex items-start gap-4">
        <div className="rounded-2xl bg-[#f4c430]/20 p-3 text-[#002b5c]">
          <Bell size={22} />
        </div>

        <div className="flex-1">
          <div className="flex flex-col justify-between gap-2 md:flex-row md:items-start">
            <div>
              <h3 className="text-lg font-extrabold text-[#002b5c]">
                {notification.title || "Smart Campus Notification"}
              </h3>

              <p className="mt-2 leading-7 text-slate-600">
                {notification.message || "A new platform event was received."}
              </p>
            </div>

            <SourceBadge source={notification.sourceService} />
          </div>

          <div className="mt-4 flex flex-wrap items-center gap-3 text-sm text-slate-500">
            <span className="flex items-center gap-2">
              <CheckCircle2 size={16} className="text-green-600" />
              Delivered
            </span>

            <span className="flex items-center gap-2">
              <Clock size={16} />
              {formatDate(notification.createdAt)}
            </span>
          </div>
        </div>
      </div>
    </div>
  );
}

function SourceBadge({ source }: { source?: string }) {
  const label = source || "notification-service";

  return (
    <span className="w-fit rounded-full bg-[#002b5c]/10 px-3 py-1 text-xs font-bold text-[#002b5c]">
      {label}
    </span>
  );
}

function formatDate(value?: string) {
  if (!value) return "Recently";

  const date = new Date(value);

  if (Number.isNaN(date.getTime())) return "Recently";

  return date.toLocaleString();
}

function InfoCard({
  icon,
  title,
  value,
  text,
}: {
  icon: React.ReactNode;
  title: string;
  value: string | number;
  text: string;
}) {
  return (
    <div className="rounded-3xl bg-white p-6 shadow-sm ring-1 ring-slate-200">
      <div className="mb-4 inline-flex rounded-2xl bg-[#f4c430]/20 p-4 text-[#002b5c]">
        {icon}
      </div>

      <p className="text-sm font-bold uppercase tracking-[0.18em] text-slate-400">
        {title}
      </p>

      <h2 className="mt-2 text-3xl font-extrabold text-[#002b5c]">{value}</h2>

      <p className="mt-3 text-sm leading-6 text-slate-600">{text}</p>
    </div>
  );
}

function Badge({ text }: { text: string }) {
  return (
    <span className="rounded-full bg-white/15 px-4 py-2 text-sm font-bold text-white backdrop-blur">
      {text}
    </span>
  );
}