services:
  campus-incident-db:
    image: postgres:16
    container_name: smart-campus-incident-db-prod
    environment:
      POSTGRES_DB: campus_incidents_prod
      POSTGRES_USER: incident_user
      POSTGRES_PASSWORD: 3305e31ba6dc4a048d642b6777905778
    volumes:
      - campus_incident_db_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: smart-campus-incident-redis-prod
    restart: unless-stopped

  campus-incident-service:
    image: japilataxi/campus-incident-service:prod
    container_name: smart-campus-incident-service-prod
    ports:
      - "3020:3020"
    environment:
      SERVICE_NAME: campus-incident-service
      PORT: 3020
      DATABASE_URL: postgresql://incident_user:3305e31ba6dc4a048d642b6777905778@campus-incident-db:5432/campus_incidents_prod
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: 2c31950dd72e455aa92bd4edf55948e0
    depends_on:
      - campus-incident-db
      - redis
    restart: unless-stopped

volumes:
  campus_incident_db_data: