services:
  
  transport-service:
    image: japilataxi/transport-service:qa
    container_name: smart-campus-transport-service-qa
    ports:
      - "3022:3022"
    environment:
      SERVICE_NAME: transport-service
      PORT: 3022
      DATABASE_URL: postgresql://transport_user:transport_password@transport-db:5432/transport_db
      REDIS_HOST: core3-redis
      REDIS_PORT: 6379
      RABBITMQ_URL: amqp://guest:guest@${RABBITMQ_HOST}:5672
      RABBITMQ_EXCHANGE: smart-campus.events
    depends_on:
      - transport-db
      - core3-redis
    restart: unless-stopped

  space-availability-service:
    image: japilataxi/space-availability-service:qa
    container_name: smart-campus-space-availability-service-qa
    ports:
      - "3023:3023"
    environment:
      SERVICE_NAME: space-availability-service
      NODE_ENV: development
      PORT: 3023
      DATABASE_URL: postgresql://space_user:space_password@space-availability-db:5432/space_availability_db
      REDIS_HOST: core3-redis
      REDIS_PORT: 6379
      RABBITMQ_URL: amqp://guest:guest@${RABBITMQ_HOST}:5672
      RABBITMQ_EXCHANGE: smart-campus.events
    depends_on:
      - space-availability-db
      - core3-redis
    restart: unless-stopped

  transport-db:
    image: postgres:16
    container_name: smart-campus-transport-db-qa
    environment:
      POSTGRES_DB: transport_db
      POSTGRES_USER: transport_user
      POSTGRES_PASSWORD: transport_password
    volumes:
      - transport_db_data:/var/lib/postgresql/data
    restart: unless-stopped

  space-availability-db:
    image: postgres:16
    container_name: smart-campus-space-availability-db-qa
    environment:
      POSTGRES_DB: space_availability_db
      POSTGRES_USER: space_user
      POSTGRES_PASSWORD: space_password
    volumes:
      - space_availability_db_data:/var/lib/postgresql/data
    restart: unless-stopped

  core3-redis:
    image: redis:7-alpine
    container_name: smart-campus-core3-redis-qa
    restart: unless-stopped

volumes:
  transport_db_data:
  space_availability_db_data:
