services:
  space-availability-db:
    image: postgres:16
    container_name: smart-campus-space-availability-db-qa
    environment:
      POSTGRES_DB: space_availability_db
      POSTGRES_USER: space_user
      POSTGRES_PASSWORD: space_password
    volumes:
      - space_availability_db_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: smart-campus-space-availability-redis-qa
    restart: unless-stopped


  space-availability-service:
    image: japilataxi/space-availability-service:qa
    container_name: smart-campus-space-availability-service-qa
    ports:
      - "3023:3023"
    environment:
      SERVICE_NAME: space-availability-service
      PORT: 3023
      DATABASE_URL: postgresql://space_user:space_password@space-availability-db:5432/space_availability_db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RABBITMQ_URL: ${RABBITMQ_URL}
      RABBITMQ_EXCHANGE: smart-campus.events
      JWT_SECRET: change_me
    depends_on:
      - space-availability-db
      - redis
    restart: unless-stopped

volumes:
  space_availability_db_data: