services:
  auth-db:
    image: postgres:16
    container_name: smart-campus-auth-db-qa
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_password
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: smart-campus-auth-redis-qa
    restart: unless-stopped

  auth-service:
    image: japilataxi/auth-service:qa
    container_name: smart-campus-auth-service-qa
    ports:
      - "3001:3001"
    environment:
      SERVICE_NAME: auth-service
      PORT: 3001
      DATABASE_URL: postgresql://auth_user:auth_password@auth-db:5432/auth_db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: change_me
      JWT_REFRESH_SECRET: change_me_refresh
      ADMIN_EMAILS: kevin.amaguana@uce.edu.ec,japilataxi@uce.edu.ec,admin2026@uce.edu.ec
      RABBITMQ_URL: ${RABBITMQ_URL}
      RABBITMQ_EXCHANGE: smart-campus.events
    depends_on:
      - auth-db
      - redis
    restart: unless-stopped

volumes:
  auth_db_data: