services:

  api-gateway:
    build:
      context: ../../
      dockerfile: apps/api-gateway/Dockerfile
      args:
        APP_NAME: api-gateway
    ports:
      - "3000:3000"
    environment:
      SERVICE_NAME: api-gateway
      PORT: 3000
      AUTH_SERVICE_URL: http://auth-service:3001
      LIBRARY_SERVICE_URL: http://library-service:3002
    depends_on:
      - auth-service
      - library-service

  auth-service:
    build:
      context: ../../
      dockerfile: apps/auth-service/Dockerfile
      args:
        APP_NAME: auth-service
    ports:
      - "3001:3001"
    environment:
      SERVICE_NAME: auth-service
      PORT: 3001
      DATABASE_URL: postgresql://auth_user:auth_password@auth-db:5432/auth_db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: change_me
      JWT_REFRESH_SECRET: change_me_refresh
      ADMIN_EMAILS: kevin.amaguana@uce.edu.ec,japilataxi@uce.edu.ec,admin2026@uce.edu.ec
    depends_on:
      - auth-db
      - redis

  library-service:
    build:
      context: ../../
      dockerfile: apps/library-service/Dockerfile
      args:
        APP_NAME: library-service
    ports:
      - "3002:3002"
    environment:
      SERVICE_NAME: library-service
      PORT: 3002
      DATABASE_URL: postgresql://library_user:library_password@library-db:5432/library_db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: change_me
    depends_on:
      - library-db
      - redis

  web-app:
    build:
      context: ../../
      dockerfile: apps/web-app/Dockerfile
    ports:
      - "3003:3003"
    environment:
      PORT: 3003
      HOSTNAME: 0.0.0.0
      NEXT_PUBLIC_API_URL: http://localhost:3000
    depends_on:
      - api-gateway

  auth-db:
    image: postgres:16
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_password
    ports:
      - "5433:5432"

  library-db:
    image: postgres:16
    environment:
      POSTGRES_DB: library_db
      POSTGRES_USER: library_user
      POSTGRES_PASSWORD: library_password
    ports:
      - "5434:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3005:3000"