services:
  auth-db:
    image: postgres:16
    container_name: smart-campus-auth-db-prod
    environment:
      POSTGRES_DB: auth_prod
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: 4141abe9f3124b74bb232632df1ac2a9
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: smart-campus-auth-redis-prod
    restart: unless-stopped

  auth-service:
    image: japilataxi/auth-service:prod
    container_name: smart-campus-auth-service-prod
    ports:
      - "3001:3001"
    environment:
      SERVICE_NAME: auth-service
      PORT: 3001
      DATABASE_URL: postgresql://auth_user:4141abe9f3124b74bb232632df1ac2a9@auth-db:5432/auth_prod
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: 2c31950dd72e455aa92bd4edf55948e0
      JWT_REFRESH_SECRET: 8e0f1a2b3c4d5e6f7g8h9i0j1k2l3m4n5o6p7q8r9s0t1u2v3w4x5y6z7
      ADMIN_EMAILS: japilataxi@uce.edu.ec,admin2026@uce.edu.ec
    depends_on:
      - auth-db
      - redis
    restart: unless-stopped

volumes:
  auth_db_data: