services:
  library-db:
    image: postgres:16
    container_name: smart-campus-library-db-qa
    environment:
      POSTGRES_DB: library_db
      POSTGRES_USER: library_user
      POSTGRES_PASSWORD: library_password
    volumes:
      - library_db_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: smart-campus-library-redis-qa
    restart: unless-stopped

  library-service:
    image: japilataxi/library-service:qa
    container_name: smart-campus-library-service-qa
    ports:
      - "3002:3002"
    environment:
      SERVICE_NAME: library-service
      PORT: 3002
      DATABASE_URL: postgresql://library_user:library_password@library-db:5432/library_db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: change_me
    depends_on:
      - library-db
      - redis
    restart: unless-stopped

volumes:
  library_db_data: