name: CI

on:
  push:
    branches:
      - dev
      - qa
      - main
      - "feature/**"

  pull_request:
    branches:
      - dev
      - qa
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      postgres-auth:
        image: postgres:16
        env:
          POSTGRES_DB: auth_db
          POSTGRES_USER: auth_user
          POSTGRES_PASSWORD: auth_password
        ports:
          - 5433:5432

      postgres-library:
        image: postgres:16
        env:
          POSTGRES_DB: library_db
          POSTGRES_USER: library_user
          POSTGRES_PASSWORD: library_password
        ports:
          - 5434:5432

      postgres-qr-access:
        image: postgres:16
        env:
          POSTGRES_DB: qr_access_db
          POSTGRES_USER: qr_access_user
          POSTGRES_PASSWORD: qr_access_password
        ports:
          - 5437:5432

      postgres-transport:
        image: postgres:16
        env:
          POSTGRES_DB: transport_db
          POSTGRES_USER: transport_user
          POSTGRES_PASSWORD: transport_password
        ports:
          - 5438:5432

      postgres-workflow:
        image: postgres:16
        env:
          POSTGRES_DB: workflow_db
          POSTGRES_USER: workflow_user
          POSTGRES_PASSWORD: workflow_password
        ports:
          - 5440:5432

      postgres-space-availability:
        image: postgres:16
        env:
          POSTGRES_DB: space_availability_db
          POSTGRES_USER: space_user
          POSTGRES_PASSWORD: space_password
        ports:
          - 5439:5432
      redis:
        image: redis:7
        ports:
          - 6379:6379
      
      postgres-notification:
        image: postgres:16
        env:
          POSTGRES_DB: notification_db
          POSTGRES_USER: notification_user
          POSTGRES_PASSWORD: notification_password
        ports:
          - 5435:5432

      postgres-incident:
        image: postgres:16
        env:
          POSTGRES_DB: campus_incidents_db
          POSTGRES_USER: incident_user
          POSTGRES_PASSWORD: incident_password
        ports:
          - 5436:5432

      rabbitmq:
        image: rabbitmq:3-management-alpine
        ports:
          - 5672:5672
          - 15672:15672

    env:
      AUTH_DATABASE_URL: postgresql://auth_user:auth_password@localhost:5433/auth_db
      LIBRARY_DATABASE_URL: postgresql://library_user:library_password@localhost:5434/library_db
      QR_ACCESS_DATABASE_URL: postgresql://qr_access_user:qr_access_password@localhost:5437/qr_access_db
      TRANSPORT_DATABASE_URL: postgresql://transport_user:transport_password@localhost:5438/transport_db
      SPACE_AVAILABILITY_DATABASE_URL: postgresql://space_user:space_password@localhost:5439/space_availability_db
      WORKFLOW_DATABASE_URL: postgresql://workflow_user:workflow_password@localhost:5440/workflow_db
      DATABASE_URL: postgresql://auth_user:auth_password@localhost:5433/auth_db
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      JWT_SECRET: test_secret
      JWT_REFRESH_SECRET: test_refresh_secret
      ADMIN_EMAILS: japilataxi@uce.edu.ec,admin2026@uce.edu.ec
      NEXT_PUBLIC_API_URL: http://localhost:3000/api
      NOTIFICATION_DATABASE_URL: postgresql://notification_user:notification_password@localhost:5435/notification_db
      INCIDENT_DATABASE_URL: postgresql://incident_user:incident_password@localhost:5436/campus_incidents_db
      RABBITMQ_URL: amqp://guest:guest@localhost:5672
      RABBITMQ_EXCHANGE: smart-campus.events
      NOTIFICATION_SERVICE_URL: http://localhost:3010
      CAMPUS_INCIDENT_SERVICE_URL: http://localhost:3020
      WORKFLOW_SERVICE_URL: http://localhost:3024
      N8N_INCIDENT_WEBHOOK_URL: http://localhost:5678/webhook/incident-created-workflow
      N8N_USER_REGISTERED_WEBHOOK_URL: http://localhost:5678/webhook/user-registered-workflow
      N8N_LIBRARY_LOAN_WEBHOOK_URL: http://localhost:5678/webhook/library-loan-created-workflow
      N8N_CRITICAL_NOTIFICATION_WEBHOOK_URL: http://localhost:5678/webhook/critical-notification-workflow

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 11.5.1

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build backend and web
        run: |
          pnpm --filter api-gateway build
          pnpm --filter auth-service build
          pnpm --filter library-service build
          pnpm --filter qr-access-service build
          pnpm --filter transport-service build
          pnpm --filter space-availability-service build
          pnpm --filter workflow-service build
          pnpm --filter web-app build
          pnpm --filter campus-incident-service build
          pnpm --filter notification-service build

      - name: Run unit tests
        run: |
          pnpm --filter api-gateway test
          pnpm --filter auth-service test
          pnpm --filter library-service test
          pnpm --filter qr-access-service test
          pnpm --filter transport-service test
          pnpm --filter space-availability-service test
          pnpm --filter workflow-service test
          pnpm --filter campus-incident-service test
          pnpm --filter notification-service test

      - name: Run e2e tests
        run: |
          pnpm --filter auth-service test:e2e
          pnpm --filter library-service test:e2e
          pnpm --filter qr-access-service test:e2e
          pnpm --filter transport-service test
          pnpm --filter space-availability-service test
          pnpm --filter workflow-service test:e2e
          pnpm --filter campus-incident-service test:e2e
          pnpm --filter notification-service test:e2e



